# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: xenial
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
cache: packages
r_packages:
  - covr
r_github_packages:
  - bergant/datamodelr
  - mrc-ide/eppasm
  - mrc-ide/specio
